core:
  build: ./core
  restart: always
  ports:
    - "25:25"
    - "143:143"
    - "587:587"
  volumes:
    - /opt/dockermail/settings:/mail_settings
    - /opt/dockermail/vmail:/vmail
  links:
   - opendkim
   # - amavis
opendkim:
  build: ./opendkim
  restart: always
  volumes:
    - /opt/dockermail/settings:/mail_settings
#amavis:
#  build: ./amavis
#  restart: always
#  volumes:
#    - /opt/dockermail/settings:/mail_settings
